apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: farank338/iot_cnd_hw2:latest
        ports:
        - containerPort: 8080
        env:        
        - name: DB_HOST_IP
          value: "database-service"
        - name: DB_HOST_PORT
          value: "5432"
        - name: USER_DB_NAME
          value: "username"
        - name: USER_DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "default_database"
        - name: DB_TIMEZONE
          value: "Europe/Moscow"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
