version: '3'

services:
  web:
    build: .
    image: farank338/iot_cnd_hw2

    ports:
      - '8080:8080'    
    environment:      
      DB_HOST_IP: database
      DB_HOST_PORT: 5432
      USER_DB_NAME: username
      USER_DB_PASSWORD: password
      DB_NAME: default_database
      DB_TIMEZONE: Europe/Moscow
 
  database:
   
    image: 'postgres:latest'
  
    expose:
      - "5432"
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)

   